controllers/ImageController.php
<?php

namespace app\controllers;


use app\models\UploadForm;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class ImageController extends Controller
{
    public function actionIndex()
    {
        $images = UploadForm::find()->all();
        $model = new UploadForm();
        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');

            if ($model->validate()) {
                $model->filename = $model->file->baseName . '.' . $model->file->extension;
                $model->save();
                $model->file->saveAs(Yii::getAlias('@webroot').'/upload/' . $model->file->baseName . '.' . $model->file->extension);
                return $this->actionAlbum();
            }
        }
        return $this->render('index',[
            'model' => $model,
            'images' => $images
        ]);
    }

    public function actionAlbum()
    {
        $images = UploadForm::find()->all();
        return $this->render('album',[
            'images' => $images
        ]);
    }
    public function actionDelete($id)
    {
        $model = UploadForm::findOne(['id' => $id]);
        $model->delete();

        return $this->redirect(['album']);
    }




}

views/image/album.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = 'Album';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="image-album">
    <?= Html::a('<i class="fa fa-upload"></i>Загрузить новый', ['image/index'], ['class' => 'btn btn-info']) ?>
        <div class="container" style="margin-top:40px;">
            <h2>Cписка фотографий</h2>
            <div class="demo-gallery">
                <ul id="lightgallery" class="list-unstyled row">
                    <?php foreach ($images as $img):?>
                        <li class="col-md-6">
                            <img id="<?=$img->id?>" class="img-responsive" src=<?=Yii::getAlias('@web').'/upload/'.$img->filename;?>>
                            <br />
                            <?= Html::a('Удалить', ['image/delete','id'=>$img->id], ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('Поворот', [''], ['class' => 'btn btn-warning','id' => 'rotate']) ?>
                            <br />
                        </li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
</div>

<?php
$this->registerCss('
.spinEffect{
   transform: rotate(180deg);
   -webkit-transform: rotate(180deg);
   -ms-transform: rotate(180deg);
}
');
$this->registerJs('
$(\'#lightgallery #rotate\').click(function(e){
    e.preventDefault();
    let degri = 0;
    let a = "#";
    let id = a + e.target.parentElement.childNodes[1].id;
    $(id).toggleClass("spinEffect");
    
 
});

');
?>

views/image/index.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

$this->title = 'Index';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="image-index">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'file')->fileInput() ?>

    <?= Html::submitButton('Загрузить', ['class' => 'btn btn-success']) ?>
    <?= Html::a('Посмотреть Альбом', ['image/album'], ['class' => 'btn btn-info']) ?>
    <?php ActiveForm::end(); ?>
    <br />

</div>